package com.yzz.adventure.green;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.yzz.adventure.model.Bag;
import com.yzz.adventure.model.Box;
import com.yzz.adventure.model.GameContext;
import com.yzz.adventure.model.Item;
import com.yzz.adventure.model.Monster;
import com.yzz.adventure.model.Pet;
import com.yzz.adventure.model.Player;
import com.yzz.adventure.model.Stroy;

import com.yzz.adventure.green.BagDao;
import com.yzz.adventure.green.BoxDao;
import com.yzz.adventure.green.GameContextDao;
import com.yzz.adventure.green.ItemDao;
import com.yzz.adventure.green.MonsterDao;
import com.yzz.adventure.green.PetDao;
import com.yzz.adventure.green.PlayerDao;
import com.yzz.adventure.green.StroyDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig bagDaoConfig;
    private final DaoConfig boxDaoConfig;
    private final DaoConfig gameContextDaoConfig;
    private final DaoConfig itemDaoConfig;
    private final DaoConfig monsterDaoConfig;
    private final DaoConfig petDaoConfig;
    private final DaoConfig playerDaoConfig;
    private final DaoConfig stroyDaoConfig;

    private final BagDao bagDao;
    private final BoxDao boxDao;
    private final GameContextDao gameContextDao;
    private final ItemDao itemDao;
    private final MonsterDao monsterDao;
    private final PetDao petDao;
    private final PlayerDao playerDao;
    private final StroyDao stroyDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        bagDaoConfig = daoConfigMap.get(BagDao.class).clone();
        bagDaoConfig.initIdentityScope(type);

        boxDaoConfig = daoConfigMap.get(BoxDao.class).clone();
        boxDaoConfig.initIdentityScope(type);

        gameContextDaoConfig = daoConfigMap.get(GameContextDao.class).clone();
        gameContextDaoConfig.initIdentityScope(type);

        itemDaoConfig = daoConfigMap.get(ItemDao.class).clone();
        itemDaoConfig.initIdentityScope(type);

        monsterDaoConfig = daoConfigMap.get(MonsterDao.class).clone();
        monsterDaoConfig.initIdentityScope(type);

        petDaoConfig = daoConfigMap.get(PetDao.class).clone();
        petDaoConfig.initIdentityScope(type);

        playerDaoConfig = daoConfigMap.get(PlayerDao.class).clone();
        playerDaoConfig.initIdentityScope(type);

        stroyDaoConfig = daoConfigMap.get(StroyDao.class).clone();
        stroyDaoConfig.initIdentityScope(type);

        bagDao = new BagDao(bagDaoConfig, this);
        boxDao = new BoxDao(boxDaoConfig, this);
        gameContextDao = new GameContextDao(gameContextDaoConfig, this);
        itemDao = new ItemDao(itemDaoConfig, this);
        monsterDao = new MonsterDao(monsterDaoConfig, this);
        petDao = new PetDao(petDaoConfig, this);
        playerDao = new PlayerDao(playerDaoConfig, this);
        stroyDao = new StroyDao(stroyDaoConfig, this);

        registerDao(Bag.class, bagDao);
        registerDao(Box.class, boxDao);
        registerDao(GameContext.class, gameContextDao);
        registerDao(Item.class, itemDao);
        registerDao(Monster.class, monsterDao);
        registerDao(Pet.class, petDao);
        registerDao(Player.class, playerDao);
        registerDao(Stroy.class, stroyDao);
    }
    
    public void clear() {
        bagDaoConfig.clearIdentityScope();
        boxDaoConfig.clearIdentityScope();
        gameContextDaoConfig.clearIdentityScope();
        itemDaoConfig.clearIdentityScope();
        monsterDaoConfig.clearIdentityScope();
        petDaoConfig.clearIdentityScope();
        playerDaoConfig.clearIdentityScope();
        stroyDaoConfig.clearIdentityScope();
    }

    public BagDao getBagDao() {
        return bagDao;
    }

    public BoxDao getBoxDao() {
        return boxDao;
    }

    public GameContextDao getGameContextDao() {
        return gameContextDao;
    }

    public ItemDao getItemDao() {
        return itemDao;
    }

    public MonsterDao getMonsterDao() {
        return monsterDao;
    }

    public PetDao getPetDao() {
        return petDao;
    }

    public PlayerDao getPlayerDao() {
        return playerDao;
    }

    public StroyDao getStroyDao() {
        return stroyDao;
    }

}
