package com.yzz.adventure.green;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.yzz.adventure.model.Pet;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "PET".
*/
public class PetDao extends AbstractDao<Pet, Long> {

    public static final String TABLENAME = "PET";

    /**
     * Properties of entity Pet.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property _Id = new Property(0, Long.class, "_Id", true, "_id");
    }


    public PetDao(DaoConfig config) {
        super(config);
    }
    
    public PetDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"PET\" (" + //
                "\"_id\" INTEGER PRIMARY KEY );"); // 0: _Id
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"PET\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Pet entity) {
        stmt.clearBindings();
 
        Long _Id = entity.get_Id();
        if (_Id != null) {
            stmt.bindLong(1, _Id);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Pet entity) {
        stmt.clearBindings();
 
        Long _Id = entity.get_Id();
        if (_Id != null) {
            stmt.bindLong(1, _Id);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Pet readEntity(Cursor cursor, int offset) {
        Pet entity = new Pet( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0) // _Id
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Pet entity, int offset) {
        entity.set_Id(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Pet entity, long rowId) {
        entity.set_Id(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Pet entity) {
        if(entity != null) {
            return entity.get_Id();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Pet entity) {
        return entity.get_Id() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
